"""
PDF生成器
将结构化内容生成为PDF文档
使用 fpdf2 库，支持中文
"""
from fpdf import FPDF
from pathlib import Path
from typing import List, Optional
from datetime import datetime

from ..models import StructuredContent, LegalSection
from ..config import Config


class ChinesePDF(FPDF):
    """支持中文的PDF类"""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        """页眉"""
        if self.page_no() == 1:
            return  # 首页不显示页眉

        self.set_font('helvetica', '', 9)
        self.set_text_color(128, 128, 128)
        # 使用英文避免字体问题
        self.cell(0, 10, 'Legal Rights Knowledge Base', 0, 0, 'L')
        self.ln(15)

    def footer(self):
        """页脚"""
        self.set_y(-15)
        self.set_font('helvetica', '', 8)
        self.set_text_color(128, 128, 128)
        page_text = f'Page {self.page_no()}/{{nb}}'
        self.cell(0, 10, page_text, 0, 0, 'C')

    def chapter_title(self, title: str, level: int = 1):
        """章节标题"""
        # 根据层级设置字体大小
        sizes = {1: 16, 2: 14, 3: 12, 4: 11, 5: 10, 6: 10}
        size = sizes.get(level, 10)

        # 添加垂直间距
        if level == 1:
            self.ln(10)
        elif level == 2:
            self.ln(8)
        else:
            self.ln(5)

        self.set_font('helvetica', 'B', size)
        self.set_text_color(0, 0, 0)

        # 添加标题前缀（层级缩进）
        indent = '  ' * (level - 1)
        self.multi_cell(0, 8, f'{indent}{title}')
        self.ln(3)

    def chapter_body(self, text: str):
        """章节内容"""
        if not text or not text.strip():
            return

        self.set_font('helvetica', '', 10)
        self.set_text_color(50, 50, 50)

        # 分段处理
        paragraphs = text.split('\n\n')
        for para in paragraphs:
            para = para.strip()
            if para:
                self.multi_cell(0, 6, para)
                self.ln(3)


class PDFGenerator:
    """PDF生成器"""

    def __init__(self):
        """初始化生成器"""
        self.output_dir = Config.KNOWLEDGE_DIR

    def _sanitize_filename(self, title: str) -> str:
        """清理文件名"""
        # 移除不允许的字符
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            title = title.replace(char, '')

        # 限制长度
        if len(title) > 50:
            title = title[:50]

        return title.strip()

    def generate(
        self,
        content: StructuredContent,
        output_path: Optional[Path] = None
    ) -> Path:
        """
        生成PDF文档

        Args:
            content: 结构化内容
            output_path: 输出路径（如果为None则自动生成）

        Returns:
            生成的PDF文件路径
        """
        # 确定输出路径
        if output_path is None:
            filename = self._sanitize_filename(content.title) + '.pdf'
            output_path = self.output_dir / filename

        print(f"📄 生成PDF: {content.title}")
        print(f"   输出: {output_path}")

        # 创建PDF
        pdf = ChinesePDF()
        pdf.add_page()

        # 设置默认字体
        pdf.set_font('helvetica', '', 10)

        # 生成封面
        self._add_cover_page(pdf, content)

        # 生成目录
        self._add_toc_page(pdf, content)

        # 生成内容页
        self._add_content_pages(pdf, content)

        # 保存PDF
        pdf.output(str(output_path))

        file_size = output_path.stat().st_size
        print(f"   ✅ 生成完成 ({file_size:,} 字节)")

        return output_path

    def _add_cover_page(self, pdf: ChinesePDF, content: StructuredContent):
        """添加封面页"""
        pdf.set_font('helvetica', 'B', 24)
        pdf.ln(60)
        pdf.cell(0, 20, content.title, 0, 1, 'C')

        pdf.set_font('helvetica', '', 12)
        pdf.set_text_color(100, 100, 100)
        pdf.ln(10)

        # 元数据 (使用英文避免字体问题)
        pdf.cell(0, 8, f'Source: {content.url}', 0, 1, 'C')
        pdf.cell(0, 8, f'Date: {content.scraped_at.strftime("%Y-%m-%d")}', 0, 1, 'C')
        pdf.cell(0, 8, f'Sections: {len(content.sections)}', 0, 1, 'C')

        pdf.ln(20)
        pdf.set_font('helvetica', '', 10)
        pdf.multi_cell(
            0, 6,
            'Generated by Legal Rights AI Assistant\n'
            'For reference only - Please consult professional lawyers',
            0, 'C'
        )

        # 添加新页
        pdf.add_page()

    def _add_toc_page(self, pdf: ChinesePDF, content: StructuredContent):
        """添加目录页"""
        pdf.set_font('helvetica', 'B', 18)
        pdf.cell(0, 15, 'Table of Contents', 0, 1, 'C')
        pdf.ln(10)

        pdf.set_font('helvetica', '', 10)

        def add_section_to_toc(section: LegalSection, level: int):
            """递归添加章节到目录"""
            indent = '  ' * (level - 1)
            prefix = '-' * level

            # 章节标题
            pdf.set_text_color(0, 0, 0)
            title_text = f'{indent}{prefix} {section.title}'
            pdf.multi_cell(0, 6, title_text)

            # 递归处理子章节
            for subsection in section.subsections:
                add_section_to_toc(subsection, level + 1)

        for section in content.sections:
            add_section_to_toc(section, 1)

        pdf.add_page()

    def _add_content_pages(self, pdf: ChinesePDF, content: StructuredContent):
        """添加内容页"""

        def add_section(section: LegalSection):
            """递归添加章节内容"""
            # 添加标题
            pdf.chapter_title(section.title, section.level)

            # 添加内容
            if section.content:
                pdf.chapter_body(section.content)

            # 递归处理子章节
            for subsection in section.subsections:
                add_section(subsection)

        for section in content.sections:
            add_section(section)

    def generate_batch(
        self,
        contents: List[StructuredContent]
    ) -> List[Path]:
        """
        批量生成PDF

        Args:
            contents: 结构化内容列表

        Returns:
            生成的PDF文件路径列表
        """
        print(f"\n📚 批量生成 {len(contents)} 个PDF文档")
        print("=" * 70)

        output_paths = []

        for i, content in enumerate(contents, 1):
            print(f"\n[{i}/{len(contents)}]")
            try:
                path = self.generate(content)
                output_paths.append(path)
            except Exception as e:
                print(f"   ❌ 生成失败: {e}")

        print("\n" + "=" * 70)
        print(f"✅ 完成: 成功 {len(output_paths)}/{len(contents)}")

        return output_paths
